### ISSUE TITLE
json-ld tests fail on NoSuchFieldError: HTML

### ISSUE THREAD

**Issue by barmintor** [cavendish-ldp/cavendish#7]
2016-09-20 08:02:18 WARN  HttpChannel:468 - //localhost:8888/cb323adfd6df03f9
java.lang.NoSuchFieldError: HTML
    at org.openrdf.rio.datatypes.RDFDatatypeHandler.isRecognizedDatatype(RDFDatatypeHandler.java:49)
    at org.openrdf.rio.helpers.RDFParserHelper.createLiteral(RDFParserHelper.java:198)
    at org.openrdf.rio.helpers.RDFParserHelper.createLiteral(RDFParserHelper.java:86)
    at org.openrdf.rio.jsonld.JSONLDInternalTripleCallback.triple(JSONLDInternalTripleCallback.java:132)
    at org.openrdf.rio.jsonld.JSONLDInternalTripleCallback.call(JSONLDInternalTripleCallback.java:226)
    at com.github.jsonldjava.core.JsonLdProcessor.toRDF(JsonLdProcessor.java:494)
    at org.openrdf.rio.jsonld.JSONLDParser.parse(JSONLDParser.java:78)
    at cavendish.jetty.handler.LdpHandler.parseRDFBody(LdpHandler.java:459)
    at cavendish.jetty.handler.LdpHandler.createResource(LdpHandler.java:374)
    at cavendish.jetty.handler.LdpHandler.doPOST(LdpHandler.java:369)
    at cavendish.jetty.handler.LdpHandler.handle(LdpHandler.java:155)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
    at org.eclipse.jetty.server.Server.handle(Server.java:517)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
    at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
    at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
    at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
    at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
    at java.lang.Thread.run(Thread.java:745)
testPostJsonLd                                     IndirectContainer Failed   [MUST]              11ms

**Comment by barmintor** [comment]
Missing field/enum appears to be from sesame jsonld dependency falling out of line with other sesame dependencies.

**Comment by barmintor** [comment]
sesame json ld impl requires version 2.8, is not compatible with 2.7 required by blazegraph; use github impl
